
DROP TABLE IF EXISTS person_language;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS language;
DROP TABLE IF EXISTS country;

-- Country table
CREATE TABLE country (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    iso_code CHAR(2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Address table
CREATE TABLE address (
    id SERIAL PRIMARY KEY,
    street VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    zipcode VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Language table
CREATE TABLE language (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    iso_code CHAR(2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Person table (no country column yet)
CREATE TABLE person (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    surname VARCHAR(100),
    birthdate DATE,
    email VARCHAR(100),
    phone VARCHAR(50),
    country_id INTEGER REFERENCES country(id),
    address_id INTEGER REFERENCES address(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Join table: person-language (many-to-many)
CREATE TABLE person_language (
    person_id INTEGER REFERENCES person(id) ON DELETE CASCADE,
    language_id INTEGER REFERENCES language(id) ON DELETE CASCADE,
    PRIMARY KEY (person_id, language_id)
);

-- Insert ISO 639-1 languages
INSERT INTO language (name, iso_code) VALUES
('English', 'en'),
('Afar', 'aa'),
('Abkhazian', 'ab'),
('Afrikaans', 'af'),
('Amharic', 'am'),
('Arabic', 'ar'),
('Assamese', 'as'),
('Aymara', 'ay'),
('Azerbaijani', 'az'),
('Bashkir', 'ba'),
('Belarusian', 'be'),
('Bulgarian', 'bg'),
('Bihari', 'bh'),
('Bislama', 'bi'),
('Bengali/Bangla', 'bn'),
('Tibetan', 'bo'),
('Breton', 'br'),
('Catalan', 'ca'),
('Corsican', 'co'),
('Czech', 'cs'),
('Welsh', 'cy'),
('Danish', 'da'),
('German', 'de'),
('Bhutani', 'dz'),
('Greek', 'el'),
('Esperanto', 'eo'),
('Spanish', 'es'),
('Estonian', 'et'),
('Basque', 'eu'),
('Persian', 'fa'),
('Finnish', 'fi'),
('Fiji', 'fj'),
('Faeroese', 'fo'),
('French', 'fr'),
('Frisian', 'fy'),
('Irish', 'ga'),
('Scots/Gaelic', 'gd'),
('Galician', 'gl'),
('Guarani', 'gn'),
('Gujarati', 'gu'),
('Hausa', 'ha'),
('Hindi', 'hi'),
('Croatian', 'hr'),
('Hungarian', 'hu'),
('Armenian', 'hy'),
('Interlingua', 'ia'),
('Interlingue', 'ie'),
('Inupiak', 'ik'),
('Indonesian', 'in'),
('Icelandic', 'is'),
('Italian', 'it'),
('Hebrew', 'iw'),
('Japanese', 'ja'),
('Yiddish', 'ji'),
('Javanese', 'jw'),
('Georgian', 'ka'),
('Kazakh', 'kk'),
('Greenlandic', 'kl'),
('Cambodian', 'km'),
('Kannada', 'kn'),
('Korean', 'ko'),
('Kashmiri', 'ks'),
('Kurdish', 'ku'),
('Kirghiz', 'ky'),
('Latin', 'la'),
('Lingala', 'ln'),
('Laothian', 'lo'),
('Lithuanian', 'lt'),
('Latvian/Lettish', 'lv'),
('Malagasy', 'mg'),
('Maori', 'mi'),
('Macedonian', 'mk'),
('Malayalam', 'ml'),
('Mongolian', 'mn'),
('Moldavian', 'mo'),
('Marathi', 'mr'),
('Malay', 'ms'),
('Maltese', 'mt'),
('Burmese', 'my'),
('Nauru', 'na'),
('Nepali', 'ne'),
('Dutch', 'nl'),
('Norwegian', 'no'),
('Occitan', 'oc'),
('(Afan)/Oromoor/Oriya', 'om'),
('Punjabi', 'pa'),
('Polish', 'pl'),
('Pashto/Pushto', 'ps'),
('Portuguese', 'pt'),
('Quechua', 'qu'),
('Rhaeto-Romance', 'rm'),
('Kirundi', 'rn'),
('Romanian', 'ro'),
('Russian', 'ru'),
('Kinyarwanda', 'rw'),
('Sanskrit', 'sa'),
('Sindhi', 'sd'),
('Sangro', 'sg'),
('Serbo-Croatian', 'sh'),
('Singhalese', 'si'),
('Slovak', 'sk'),
('Slovenian', 'sl'),
('Samoan', 'sm'),
('Shona', 'sn'),
('Somali', 'so'),
('Albanian', 'sq'),
('Serbian', 'sr'),
('Siswati', 'ss'),
('Sesotho', 'st'),
('Sundanese', 'su'),
('Swedish', 'sv'),
('Swahili', 'sw'),
('Tamil', 'ta'),
('Telugu', 'te'),
('Tajik', 'tg'),
('Thai', 'th'),
('Tigrinya', 'ti'),
('Turkmen', 'tk'),
('Tagalog', 'tl'),
('Setswana', 'tn'),
('Tonga', 'to'),
('Turkish', 'tr'),
('Tsonga', 'ts'),
('Tatar', 'tt'),
('Twi', 'tw'),
('Ukrainian', 'uk'),
('Urdu', 'ur'),
('Uzbek', 'uz'),
('Vietnamese', 'vi'),
('Volapuk', 'vo'),
('Wolof', 'wo'),
('Xhosa', 'xh'),
('Yoruba', 'yo'),
('Chinese', 'zh'),
('Zulu', 'zu');

-- Insert sample countries (ISO 3166-1 alpha-2)
INSERT INTO country (name, iso_code) VALUES
('Afghanistan', 'AF'),
('Albania', 'AL'),
('Algeria', 'DZ'),
('Andorra', 'AD'),
('Angola', 'AO'),
('Argentina', 'AR'),
('Armenia', 'AM'),
('Australia', 'AU'),
('Austria', 'AT'),
('Azerbaijan', 'AZ'),
('Bahamas', 'BS'),
('Bahrain', 'BH'),
('Bangladesh', 'BD'),
('Barbados', 'BB'),
('Belarus', 'BY'),
('Belgium', 'BE'),
('Belize', 'BZ'),
('Benin', 'BJ'),
('Bhutan', 'BT'),
('Bolivia', 'BO'),
('Bosnia and Herzegovina', 'BA'),
('Botswana', 'BW'),
('Brazil', 'BR'),
('Brunei', 'BN'),
('Bulgaria', 'BG'),
('Burkina Faso', 'BF'),
('Burundi', 'BI'),
('Cambodia', 'KH'),
('Cameroon', 'CM'),
('Canada', 'CA'),
('Chad', 'TD'),
('Chile', 'CL'),
('China', 'CN'),
('Colombia', 'CO'),
('Congo', 'CG'),
('Costa Rica', 'CR'),
('Croatia', 'HR'),
('Cuba', 'CU'),
('Cyprus', 'CY'),
('Czech Republic', 'CZ'),
('Denmark', 'DK'),
('Dominican Republic', 'DO'),
('Ecuador', 'EC'),
('Egypt', 'EG'),
('El Salvador', 'SV'),
('Estonia', 'EE'),
('Ethiopia', 'ET'),
('Finland', 'FI'),
('France', 'FR'),
('Georgia', 'GE'),
('Germany', 'DE'),
('Greece', 'GR'),
('Guatemala', 'GT'),
('Hungary', 'HU'),
('Iceland', 'IS'),
('India', 'IN'),
('Indonesia', 'ID'),
('Iran', 'IR'),
('Iraq', 'IQ'),
('Ireland', 'IE'),
('Israel', 'IL'),
('Italy', 'IT'),
('Jamaica', 'JM'),
('Japan', 'JP'),
('Jordan', 'JO'),
('Kazakhstan', 'KZ'),
('Kenya', 'KE'),
('Kuwait', 'KW'),
('Latvia', 'LV'),
('Lebanon', 'LB'),
('Libya', 'LY'),
('Lithuania', 'LT'),
('Luxembourg', 'LU'),
('Malaysia', 'MY'),
('Mexico', 'MX'),
('Monaco', 'MC'),
('Morocco', 'MA'),
('Nepal', 'NP'),
('Netherlands', 'NL'),
('New Zealand', 'NZ'),
('Nicaragua', 'NI'),
('Nigeria', 'NG'),
('North Korea', 'KP'),
('Norway', 'NO'),
('Oman', 'OM'),
('Pakistan', 'PK'),
('Panama', 'PA'),
('Peru', 'PE'),
('Philippines', 'PH'),
('Poland', 'PL'),
('Portugal', 'PT'),
('Qatar', 'QA'),
('Romania', 'RO'),
('Russia', 'RU'),
('Rwanda', 'RW'),
('Saudi Arabia', 'SA'),
('Senegal', 'SN'),
('Serbia', 'RS'),
('Singapore', 'SG'),
('Slovakia', 'SK'),
('Slovenia', 'SI'),
('South Africa', 'ZA'),
('South Korea', 'KR'),
('Spain', 'ES'),
('Sri Lanka', 'LK'),
('Sweden', 'SE'),
('Switzerland', 'CH'),
('Syria', 'SY'),
('Thailand', 'TH'),
('Tunisia', 'TN'),
('Turkey', 'TR'),
('Ukraine', 'UA'),
('United Arab Emirates', 'AE'),
('United Kingdom', 'GB'),
('United States', 'US'),
('Uruguay', 'UY'),
('Uzbekistan', 'UZ'),
('Vietnam', 'VN'),
('Yemen', 'YE'),
('Zambia', 'ZM'),
('Zimbabwe', 'ZW');

-- Sample Addresses
INSERT INTO address (street, city, state, zipcode) VALUES
('123 Main St', 'New York', 'NY', '10001'),
('456 Elm St', 'Los Angeles', 'CA', '90001'),
('789 Oak St', 'Chicago', 'IL', '60601');


-- Sample Persons
INSERT INTO person (name, surname, birthdate, email, phone, address_id, country_id)
VALUES
('Alice', 'Smith', '1990-05-20', 'alice@example.com', '+1234567890', 1, 1),
('Bob', 'Johnson', '1985-09-12', 'bob@example.com', '+1987654321', 2, 2),
('Charlie', 'Tanaka', '1992-03-15', 'charlie@example.jp', '+81312345678', 3, 3);

-- Sample Person-Language relations
INSERT INTO person_language (person_id, language_id) VALUES
(1, 1), -- Alice speaks English
(2, 2), -- Bob speaks German
(3, 3), -- Charlie speaks Japanese
(1, 2); -- Alice also speaks German